#!/bin/sh
echo "ready to install, last change to abort!!"
read n
curdir=`pwd`
sh ./backuptc.sh
(cd /
tar xvf ${curdir}/tc01.tar
)
(cd /dev
rm /dev/tc0a
rm /dev/tc1a
rm /dev/rtc0a
rm /dev/rtc1a
./MAKEDEV tc0
./MAKEDEV tc1
)
sh ./buildkernel.sh

echo
echo
echo please reboot to finish the driver addition
